name: Packer OCI Image Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  OCI_CLI_AUTH: api_key

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      user: ${{ secrets.OCI_USER_OCID }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_TENANCY_OCID }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_API_PRIVATE_KEY }}
      OCI_CLI_REGION: ${{ secrets.OCI_REGION }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: 'latest'

      - name: Configure OCI CLI
        run: |
          mkdir -p ~/.oci
          echo "[DEFAULT]" > ~/.oci/config
          echo "user=${{ secrets.OCI_USER_OCID }}" >> ~/.oci/config
          echo "fingerprint=${{ secrets.OCI_FINGERPRINT }}" >> ~/.oci/config
          echo "tenancy=${{ secrets.OCI_TENANCY_OCID }}" >> ~/.oci/config
          echo "region=${{ secrets.OCI_REGION }}" >> ~/.oci/config
          echo "key_file=/home/runner/.oci/oci_api_key.pem" >> ~/.oci/config
          printf "%s\n" "$OCI_CLI_KEY_CONTENT" > ~/.oci/oci_api_key.pem
          chmod 600 ~/.oci/oci_api_key.pem
          chmod 600 ~/.oci/config

      - name: Packer Init
        run: packer init .

      - name: Packer Validate
        run: |
          packer validate \
            -var-file="your_vars.pkrvars.hcl" \
            -var "availability_domain=${{ secrets.OCI_AVAILABILITY_DOMAIN }}" \
            -var "compartment_ocid=${{ secrets.OCI_COMPARTMENT_OCID }}" \
            -var "subnet_ocid=${{ secrets.OCI_SUBNET_OCID }}" \
            -var "region=${{ secrets.OCI_REGION }}" \
            .

      - name: Packer Build
        run: |
          packer build \
            -var-file="your_vars.pkrvars.hcl" \
            -var "availability_domain=${{ secrets.OCI_AVAILABILITY_DOMAIN }}" \
            -var "tenancy_ocid=${{ secrets.OCI_TENANCY_OCID }}" \
            -var "key_file=/home/runner/.oci/oci_api_key.pem" \
            -var "ocpus=${{ secrets.OCI_OCPUS }}" \
            -var "user_ocid=${{ secrets.OCI_USER_OCID }}" \
            -var "fingerprint=${{ secrets.OCI_FINGERPRINT }}" \
            -var "compartment_ocid=${{ secrets.OCI_COMPARTMENT_OCID }}" \
            -var "subnet_ocid=${{ secrets.OCI_SUBNET_OCID }}" \
            -var "region=${{ secrets.OCI_REGION }}" \
            -on-error=cleanup \
            -color=false \
            .
